/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author JoJo
 */
public class FiltroPlaca extends javax.swing.JFrame {
        static FiltroPlaca frameRegistrarOperador = new FiltroPlaca();
        static String PlacaTexto="";
        static String ReservaSeleccionada;
    /**
     * Creates new form FiltroPuntoRecogida
     */
    public FiltroPlaca() {
        initComponents();
        SedesDisponibles.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        BotónBuscar = new javax.swing.JButton();
        BotónAtrás = new javax.swing.JButton();
        SedesDisponibles = new javax.swing.JComboBox<>();
        PlacaSeleccionada = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jToggleButton2.setText("jToggleButton2");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 250));

        BotónBuscar.setText("Buscar");
        BotónBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónBuscarActionPerformed(evt);
            }
        });

        BotónAtrás.setText("Atrás");
        BotónAtrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónAtrásActionPerformed(evt);
            }
        });

        SedesDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "",PlacaTexto+"1", PlacaTexto+"2" }));
        SedesDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SedesDisponiblesActionPerformed(evt);
            }
        });

        PlacaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaSeleccionadaActionPerformed(evt);
            }
        });

        jButton1.setText("añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BotónAtrás)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotónBuscar)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SedesDisponibles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PlacaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotónAtrás)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlacaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(SedesDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(BotónBuscar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotónAtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónAtrásActionPerformed
        frameRegistrarOperador.setVisible(false); 
        PlacaSeleccionada.setText("");
        SedesDisponibles.setEnabled(false);
        SedesDisponibles.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_BotónAtrásActionPerformed

    private void BotónBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónBuscarActionPerformed
        if(PlacaTexto.equals("")){
            JOptionPane.showMessageDialog(this, "Elementos incompletos");
        } else if(SedesDisponibles.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Elementos incompletos");
        } else{
            Login.VentanaReserva(true);
            frameRegistrarOperador.setVisible(false);
            Login.frameRes.ContenidoTextoID.setText(ReservaSeleccionada);
            PlacaSeleccionada.setText("");
            SedesDisponibles.setEnabled(false);
                SedesDisponibles.setSelectedIndex(0);
        
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BotónBuscarActionPerformed

    private void SedesDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SedesDisponiblesActionPerformed
        JComboBox cb=(JComboBox)evt.getSource();
            ReservaSeleccionada=((String)cb.getSelectedItem());
            // TODO add your handling code here:
    }//GEN-LAST:event_SedesDisponiblesActionPerformed

    private void PlacaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaSeleccionadaActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_PlacaSeleccionadaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            PlacaTexto=PlacaSeleccionada.getText();
            if(!PlacaTexto.equals("")){
                SedesDisponibles.setEnabled(true);
                SedesDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "",PlacaTexto+"1", PlacaTexto+"2" }));
            }else if(PlacaTexto.equals("")){
                SedesDisponibles.setEnabled(false);
                SedesDisponibles.setSelectedIndex(0);
            }
           

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotónAtrás;
    private javax.swing.JButton BotónBuscar;
    private javax.swing.JTextField PlacaSeleccionada;
    private javax.swing.JComboBox<String> SedesDisponibles;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
