/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static GUI.Inicio.dim;
import Modelo.Reserva;
import Modelo.TEstilo;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author JoJo
 */
public class FiltroFecha extends javax.swing.JFrame {
        static FiltroFecha frameRegistrarOperador = new FiltroFecha();
        static String PlacaTexto="";
        static Reserva ReservaSeleccionada;
    /**
     * Creates new form FiltroPuntoRecogida
     */
    public FiltroFecha() {
        initComponents();
        ReservasPorFecha.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        BotónConfirmar = new javax.swing.JButton();
        BotónAtrás = new javax.swing.JButton();
        ReservasPorFecha = new javax.swing.JComboBox<>();
        botonBuscarFecha = new javax.swing.JButton();
        CalendarField = new com.toedter.calendar.JDateChooser();

        jToggleButton2.setText("jToggleButton2");

        jToggleButton1.setText("jToggleButton1");

        setTitle(" Filtrar Reserva por Fecha");
        setLocation(new java.awt.Point(0, 0));

        BotónConfirmar.setText("Consultar");
        BotónConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónConfirmarActionPerformed(evt);
            }
        });

        BotónAtrás.setText("Atrás");
        BotónAtrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotónAtrásActionPerformed(evt);
            }
        });

        ReservasPorFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservasPorFechaActionPerformed(evt);
            }
        });

        botonBuscarFecha.setText("Buscar");
        botonBuscarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotónConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReservasPorFecha, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CalendarField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(BotónAtrás, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(BotónAtrás)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalendarField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(ReservasPorFecha)
                .addGap(31, 31, 31)
                .addComponent(BotónConfirmar)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotónAtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónAtrásActionPerformed
        frameRegistrarOperador.setVisible(false); 
        CalendarField.setDate(null);
        ReservasPorFecha.setEnabled(false);
    }//GEN-LAST:event_BotónAtrásActionPerformed

    private void BotónConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotónConfirmarActionPerformed
        if(ReservasPorFecha.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "No hay una reserva seleccionada");
        } else{
            ReservaSeleccionada = (Reserva) ReservasPorFecha.getSelectedItem();
            Inicio.frameRes.ContenidoTextoID.setText(Integer.toString(ReservaSeleccionada.getNumeroFactura()));
            Inicio.frameRes.ContenidoTextoRecogida.setText(ReservaSeleccionada.getSedeRecogida());
            Inicio.frameRes.ContenidoTextoEntrega.setText(ReservaSeleccionada.getSedeEntrega());
            Inicio.frameRes.ContenidoTextoInicio.setText(ReservaSeleccionada.getFechaInicio().get(Calendar.DAY_OF_MONTH) + "/" + (ReservaSeleccionada.getFechaInicio().get(Calendar.MONTH)+1) + "/" + ReservaSeleccionada.getFechaInicio().get(Calendar.YEAR));
            Inicio.frameRes.ContenidoTextoFinal.setText(ReservaSeleccionada.getFechaFinalizacion().get(Calendar.DAY_OF_MONTH) + "/" + (ReservaSeleccionada.getFechaFinalizacion().get(Calendar.MONTH)+1) + "/" + ReservaSeleccionada.getFechaFinalizacion().get(Calendar.YEAR));
            Inicio.frameRes.ContenidoTextoSolicitud.setText(ReservaSeleccionada.getFechaSolicitud().get(Calendar.DAY_OF_MONTH) + "/" + (ReservaSeleccionada.getFechaSolicitud().get(Calendar.MONTH)+1) + "/" + ReservaSeleccionada.getFechaSolicitud().get(Calendar.YEAR));
            Inicio.frameRes.ContenidoTextoOperador.setText(ReservaSeleccionada.getOperador().toString());
            Inicio.frameRes.ContenidoTextoVehiculo.setText(ReservaSeleccionada.getVehiculoSeleccionado().toString());
            Inicio.frameRes.ContenidoTextoCliente.setText(ReservaSeleccionada.getClienteRelacionado().toString());
            TablaServiciosReserva.frameTablaServiciosPorReserva.agregarServicios(ReservaSeleccionada.getArrayServicios());
            Inicio.VentanaReserva(true);
            frameRegistrarOperador.setVisible(false);
            CalendarField.setDate(null);
            ReservasPorFecha.setEnabled(false);
            ReservasPorFecha.setSelectedIndex(0);
        
        
        }
    }//GEN-LAST:event_BotónConfirmarActionPerformed

    private void ReservasPorFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservasPorFechaActionPerformed

        ReservaSeleccionada=(Reserva)ReservasPorFecha.getSelectedItem();
    }//GEN-LAST:event_ReservasPorFechaActionPerformed

    private void botonBuscarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarFechaActionPerformed
            if(CalendarField.getCalendar()!=null){
                ReservasPorFecha.setEnabled(true);
                DefaultComboBoxModel mod= new DefaultComboBoxModel(Inicio.adminApp.filtrarReservaInicio(CalendarField.getCalendar()).toArray());
                ReservasPorFecha.setModel(mod);
                
            }else{
                ReservasPorFecha.setEnabled(false);
                ReservasPorFecha.setSelectedIndex(0);
            }
        
        
           
            
           

// TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotónAtrás;
    private javax.swing.JButton BotónConfirmar;
    private com.toedter.calendar.JDateChooser CalendarField;
    private javax.swing.JComboBox<Reserva> ReservasPorFecha;
    private javax.swing.JButton botonBuscarFecha;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
