/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Login;

/**
 *
 * @author JoJo
 */
public class TablaServiciosAsociados extends javax.swing.JFrame {
    static TablaServiciosAsociados frameVentanillaObjeto = new TablaServiciosAsociados();

    /**
     * Creates new form NewJFrame
     */
    public TablaServiciosAsociados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextoListaServicioseleccionado = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextoListaServicioseleccionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Wifi", "Seleccione vehículo Primero"},
                {"Sillas de niños", "Seleccione vehículo Primero"},
                {"Seguro", "Seleccione vehículo Primero"},
                {"GPS", "Seleccione vehículo Primero"},
                {"Asistencia en carretera", "Seleccione vehículo Primero"}
            },
            new String [] {
                "Servicios Asociados", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TextoListaServicioseleccionado.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TextoListaServicioseleccionado);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jButton1)
                .addGap(35, 164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login.VentanaEditarVehiculo(true);
        frameVentanillaObjeto.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 
     static public void correrVentanilla(){
      frameVentanillaObjeto.setVisible(true);
    }
     static public void ModificarTablaServiciosAsociados(String Servicio1,String Servicio2,String Servicio3,String Servicio4,String Servicio5){
     TextoListaServicioseleccionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Wifi", Servicio1},
                {"Sillas de niños", Servicio2},
                {"Seguro", Servicio3},
                {"GPS", Servicio4},
                {"Asistencia en carretera", Servicio5}
            },
            new String [] {
                "Servicios Asociados", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
     
     }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TextoListaServicioseleccionado;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
